
CREATE TABLE securities_master (
	id SERIAL NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	isin VARCHAR(12), 
	symbol VARCHAR(20), 
	wkn VARCHAR(20), 
	note TEXT, 
	currency VARCHAR(3) NOT NULL, 
	latest_price NUMERIC(12, 4), 
	delta_percent NUMERIC(8, 4), 
	delta_amount NUMERIC(12, 4), 
	latest_date DATE, 
	last_historical_date DATE, 
	first_historical_date DATE, 
	quote_feed_historic VARCHAR(100), 
	quote_feed_latest VARCHAR(100), 
	url_historic_quotes VARCHAR(500), 
	url_latest_quotes VARCHAR(500), 
	next_ex_date DATE, 
	next_payment_date DATE, 
	next_payment_amount NUMERIC(12, 4), 
	logo VARCHAR(500), 
	ter NUMERIC(6, 4), 
	aum NUMERIC(15, 2), 
	vendor VARCHAR(100), 
	acquisition_fee NUMERIC(6, 4), 
	management_fee NUMERIC(6, 4), 
	asset_classes_level1 VARCHAR(100), 
	asset_classes VARCHAR(200), 
	sector VARCHAR(100), 
	industry_group VARCHAR(100), 
	industry VARCHAR(100), 
	industries_gics_level4 VARCHAR(200), 
	industries_gics VARCHAR(200), 
	industries_gics_sectors_level1 VARCHAR(100), 
	industries_gics_sectors VARCHAR(200), 
	asset_allocation_level1 VARCHAR(100), 
	asset_allocation_level2 VARCHAR(100), 
	asset_allocation VARCHAR(200), 
	market VARCHAR(100), 
	region VARCHAR(100), 
	regions_msci_level3 VARCHAR(100), 
	regions_msci VARCHAR(200), 
	type_of_security_level1 VARCHAR(100), 
	type_of_security VARCHAR(200), 
	brx_plus_level1 VARCHAR(100), 
	brx_plus_level2 VARCHAR(100), 
	brx_plus VARCHAR(200), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	data_source VARCHAR(50) NOT NULL, 
	data_quality_score NUMERIC(3, 2), 
	PRIMARY KEY (id)
)




CREATE TABLE kubera_sheets (
	id SERIAL NOT NULL, 
	sheet_id VARCHAR(50) NOT NULL, 
	sheet_name VARCHAR(100) NOT NULL, 
	pp_group_name VARCHAR(100), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (sheet_id)
)




CREATE TABLE kubera_sections (
	id SERIAL NOT NULL, 
	section_id VARCHAR(50) NOT NULL, 
	section_name VARCHAR(100) NOT NULL, 
	sheet_id INTEGER NOT NULL, 
	pp_account_name VARCHAR(100), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (section_id), 
	FOREIGN KEY(sheet_id) REFERENCES kubera_sheets (id)
)




CREATE TABLE kubera_holdings (
	id SERIAL NOT NULL, 
	kubera_asset_id VARCHAR(100) NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	section_id INTEGER NOT NULL, 
	ticker VARCHAR(20), 
	ticker_id INTEGER, 
	isin VARCHAR(12), 
	category VARCHAR(50) NOT NULL, 
	sub_type VARCHAR(50) NOT NULL, 
	ticker_sub_type VARCHAR(20), 
	asset_class VARCHAR(50) NOT NULL, 
	security_type VARCHAR(50) NOT NULL, 
	exchange VARCHAR(50), 
	sector VARCHAR(100), 
	ticker_sector VARCHAR(100), 
	quantity NUMERIC(18, 8) NOT NULL, 
	current_price NUMERIC(12, 4), 
	current_value NUMERIC(15, 2) NOT NULL, 
	currency VARCHAR(3) NOT NULL, 
	cost_per_share NUMERIC(12, 4), 
	cost_basis_total NUMERIC(15, 2), 
	cost_basis_for_tax NUMERIC(15, 2), 
	irr NUMERIC(12, 6), 
	unrealized_gain_loss NUMERIC(15, 2), 
	tax_on_unrealized_gain NUMERIC(15, 2), 
	purchase_date DATE, 
	holding_period_days INTEGER, 
	tax_rate NUMERIC(5, 2), 
	tax_status VARCHAR(20), 
	geography_country VARCHAR(50), 
	geography_region VARCHAR(50), 
	liquidity VARCHAR(20), 
	investable VARCHAR(50), 
	ownership NUMERIC(3, 2), 
	aggregator VARCHAR(50), 
	provider_name VARCHAR(100), 
	provider_account_id VARCHAR(50), 
	provider_connection_id VARCHAR(50), 
	last_updated TIMESTAMP WITHOUT TIME ZONE, 
	is_manual BOOLEAN NOT NULL, 
	holdings_count INTEGER NOT NULL, 
	parent_id VARCHAR(100), 
	parent_name VARCHAR(255), 
	snapshot_date DATE NOT NULL, 
	data_source VARCHAR(50) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (kubera_asset_id), 
	FOREIGN KEY(section_id) REFERENCES kubera_sections (id)
)




CREATE TABLE holding_comparisons (
	id SERIAL NOT NULL, 
	comparison_date DATE NOT NULL, 
	pp_group VARCHAR(100) NOT NULL, 
	pp_account VARCHAR(100) NOT NULL, 
	security_name VARCHAR(255) NOT NULL, 
	isin VARCHAR(12), 
	ticker VARCHAR(20), 
	pp_quantity NUMERIC(18, 8), 
	pp_value NUMERIC(15, 2), 
	pp_currency VARCHAR(3), 
	kubera_quantity NUMERIC(18, 8), 
	kubera_value NUMERIC(15, 2), 
	kubera_currency VARCHAR(3), 
	quantity_variance NUMERIC(18, 8), 
	quantity_variance_percent NUMERIC(8, 4), 
	value_variance NUMERIC(15, 2), 
	value_variance_percent NUMERIC(8, 4), 
	is_matched BOOLEAN NOT NULL, 
	is_pp_only BOOLEAN NOT NULL, 
	is_kubera_only BOOLEAN NOT NULL, 
	variance_threshold_exceeded BOOLEAN NOT NULL, 
	quantity_tolerance_percent NUMERIC(5, 2) NOT NULL, 
	value_tolerance_percent NUMERIC(5, 2) NOT NULL, 
	notes TEXT, 
	investigation_status VARCHAR(50) NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
)

